version: '2'

services:
  postgresql:
    image: sameersbn/postgresql:9.6-2
    env_file: environment.txt
    environment:
    - DB_USER=redmine
    - DB_NAME=redmine_production
    volumes:
    - var-lib-postgresql-vol:/var/lib/postgresql

  redmine:
    image: sameersbn/redmine:3.4.2
    depends_on:
    - postgresql
    env_file: environment.txt
    environment:
    - TZ=America/Los_Angeles

    - DB_ADAPTER=postgresql
    - DB_HOST=postgresql
    - DB_PORT=5432
    - DB_USER=redmine
    - DB_NAME=redmine_production

    - REDMINE_PORT=10083
    - REDMINE_HTTPS=false
    - REDMINE_RELATIVE_URL_ROOT=
    - REDMINE_SUDO_MODE_ENABLED=false
    - REDMINE_SUDO_MODE_TIMEOUT=15
    - REDMINE_CONCURRENT_UPLOADS=2
    - REDMINE_BACKUP_SCHEDULE=daily
    - REDMINE_BACKUP_EXPIRY=
    - REDMINE_BACKUP_TIME=

    - SMTP_ENABLED=true
    - SMTP_METHOD=smtp
    - SMTP_DOMAIN=mailbot.civicknowledge.com
    - SMTP_HOST=smtp.mailgun.org
    - SMTP_PORT=25
    - SMTP_USER=postmaster@mailbot.civicknowledge.com
    - SMTP_STARTTLS=true
    - SMTP_AUTHENTICATION=:login

    - IMAP_ENABLED=true
    - IMAP_HOST=imap.gmail.com
    - IMAP_PORT=993
    - IMAP_USER=redmine@civicknowledge.com
    - IMAP_SSL=true
    - IMAP_INTERVAL=30

    ports:
    - "10083:80"
    volumes:
    - home-redmine-data-vol:/home/redmine/data
    
volumes:
    var-lib-postgresql-vol:
    home-redmine-data-vol:
